ajar-admin:
  ref:
    apiDoc: doc/api-docx.json
    db: doc/db.sql
    techRoadmap: doc/tech-roadmap-admin.md
    uxRules: doc/ux-rules-admin.md
    How: How we carry out tasks
      - if Solution write Solution
      - If there is no solution, let us define the problem
  app:  
    listings: 
      - approve_reject_with_reason:
          api: PUT /admin/listings/{id}/status
          body_example:
            status: rejected
            reason: "سبب الرفض"
      - change_status_directly:
          api: PUT /admin/listings/{id}/status
          body_example:
            status: published
      - form: 
        api:
          - GET /admin/listings/{id}
          - PUT /admin/listings/{id}
          - POST /admin/listings
          - GET /admin/categories ?
          - GET /admin/properties ?
          - GET /admin/features ?
    categories:
      features:
        - add_categories: 
          api:
            - POST /admin/categories
        - edit_categories:
          api:
            - PUT /admin/categories/{id}
        - delete_categories:
          api:
            - DELETE: /admin/categories/{id}
        - form:
        - analyze_requirements: ?
          - tableTree
          - FormCreate
          - FormEdit
        - reorder:
          api:
            - PUT: /admin/categories/{id}/reorder 
      sub:
        properties: 
          features:
            - analyze_requirements: ?
            - data_types: [integer, decimal, yes/no, date, list_of_values]
            - edit_delete_properties
          api:
            - GET: /admin/properties
            - POST: /admin/properties
            - PUT: /admin/properties/{id}
            - DELETE: /admin/properties/{id} 
        features:
          features:
            - analyze_requirements: ?
            - link_to_categories
            - reorder_drag_drop
            - edit_delete_features
          api:
            - GET: /admin/features
            - POST: /admin/features
            - PUT: /admin/features/{id}
            - DELETE: /admin/features/{id}

  bugs:
    reviews: 
      - reply_to_review:
        api: POST /admin/reviews/:id/replay
        body: { "reply": "الرد على التقييم" }
        json: { "success": false, "message": "Route not found", "key": "Route not found" }
      - approve_withhold:
        api: PUT /admin/reviews/{id}
        body: { "is_approved": true }
        json: { "success": false, "message": "ليس لديك صلاحية للقيام بهذا الإجراء", "key": "messages.permission.error" }
      - delete_messages: messages.permission.error
        api: DELETE /admin/reviews/{id}
        json: { "success": false, "message": "ليس لديك صلاحية للقيام بهذا الإجراء", "key": "messages.permission.error" } 
    sliders: 
      - delete_sliders: 
        note: Update deletion message from backend
        json: { message: "messages.slider.deleted" } 
      - reorder_drag_drop:
        note: find body in api
        api: POST /admin/sliders/reorder 
    locations: 
      - reorder_drag_drop:
        api:
          - POST: /admin/governorates/reorder
          - POST: /admin/cities/reorder
    listings:
      - reorder_drag_drop:
        api: PUT /admin/listings/reorder
    users:
      - create_user:
        api: POST /admin/users
        body: { "first_name": "Qotayba", "last_name": "Mohammad", "phone": "+96170723177", "email": "admin@admin.com", "password": "$2y$12$XyJfvYq0VuPq0ML1q5rf2.dt/2Kc5alU.u5qlQVAkC8WRSIaHacXK", "role": "user", "status": "active", "avatar": "users/68ee50c02aa89.webp" }
        json: "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '+96170723177' for key 'users.users_phone_unique' (Connection: mysql, SQL: insert into `users` (`first_name`, `last_name`, `phone`, `email`, `password`, `role`, `status`, `avatar`, `updated_at`, `created_at`) values (Qotayba, Mohammad, +96170723177, admin@admin.com, $2y$12$XyJfvYq0VuPq0ML1q5rf2.dt/2Kc5alU.u5qlQVAkC8WRSIaHacXK, user, active, users/68ee50c02aa89.webp, 2025-10-14 13:32:39, 2025-10-14 13:32:39))"

  next:
    notifications:
      features:
        - select_recipients: [all_users, selected_users]
        - set_offer_period
        - track_reads
      api:
        - GET: /admin/notifications
        - POST: /admin/notifications
        - PUT: /admin/notifications/{id}
        - DELETE: /admin/notifications/{id}
    dashboard:
      features:
        - count_listings_published
        - count_listings_pending_review
        - count_new_users
        - average_rating
        - count_whatsapp_clicks
        - view_trends_graphs
      api:
        - GET: /admin/dashboard/summary
    reports:
      features:
        - interactive_reports
        - view_graphs_charts
      api:
        - GET: /admin/reports 
